title: Minghao Xie
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/profile.jpg
description: Minghao Xie is a computer engineering PhD candidate at UCSC.
google_analytics: UA-127147641-1
plugins:
- jekyll-remote-theme