title: Minghao Xie
remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/img/profile.jpg
description: Minimal is a theme for GitHub Pages.
google_analytics: UA-127147641-1
plugins:
- jekyll-remote-theme