name: Daily Homepage Retrieval

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 markdownify

    - name: Run script
      run: |
        python sync.py

    - name: Check for changes
      id: git_diff
      run: |
        git diff --exit-code || echo "::set-output name=changes_detected::true"

    - name: Commit and push changes
      if: steps.git_diff.outputs.changes_detected == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add index.md _layouts/default.html
        git commit -m "Last update on $(date -u '+%Y-%m-%d')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-markdown:
    runs-on: ubuntu-latest
    needs: build # Optional: make it run after mirroring, or remove 'needs' to run in parallel
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your preferred Node.js version

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint index.md
        run: markdownlint index.md
